name: This is my first workflow in github action
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Execute a single command
        run: echo "Hello All"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Execute set of commands
        run: |
          hostname -s
          echo "Bye Bye"

        
